#!/bin/bash

CHAT_ID=-100225701068
BOT_TOKEN=7539902094:AAFvxXbo2v8NCLEctaC
MSGTR=53

# Detect if use ask for help
if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` \"text message\""
  exit 0
fi

if [ -z "$1" ]
  then
    echo "Add message text as second arguments"
    exit 0
fi

if [ "$#" -ne 1 ]; then
    echo "You can pass only one argument. For string with spaces put it on quotes"
    exit 0
fi

# Send the message 
curl -s --data-urlencode "text=$1" --data-urlencode "chat_id=$CHAT_ID" --data-urlencode "message_thread_id=$MSGTR" 'https://api.telegram.org/bot'$BOT_TOKEN'/sendMessage' > /dev/null

