#!/bin/bash
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
# =========================================
# Getting
#
cd
# collor status
error1="${RED} [ERROR] ${NC}"
success="${GREEN} [OK] ${NC}"
# Cek Domain
source /var/lib/airavpn/ipvps.conf
echo -e "[ ${green}INFO$NC ] Reinstall wget.."
# ==========================================
# Hapus Wget
apt update -y 
apt remove wget

# Install wget
apt install wget

clear
echo -e "Update Wget Selesai..."
cd
